<a href="https://colab.research.google.com/github/moaadouhmad99-ops/DI_Bootcamp/blob/main/Week5/Day1/Ex_XP_W5_D1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**🌟 Exercise 1 : Array Creation and Manipulation**

In [ ]:
array = np.array(range(10))
print(array)


[0 1 2 3 4 5 6 7 8 9]


**🌟 Exercise 2 : Type Conversion and Array Operations**

In [ ]:
arr = np.array([3.14, 2.17, 0, 1, 2])
arr = arr.astype(int)
print(arr)


[3 2 0 1 2]


**🌟 Exercise 3 : Working with Multi-Dimensional Arrays**

In [ ]:
arr = np.array(range(1, 10)).reshape(3, 3)
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


**🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers**

In [ ]:
arr = np.random.rand(4, 5)
arr_rounded = np.round(arr, 2)  # Arrondir à 2 décimales
print(arr_rounded)


[[0.23 0.1  0.41 0.57 0.16]
 [0.74 0.89 0.7  0.21 0.03]
 [0.02 0.07 0.62 0.29 0.12]
 [0.81 0.73 0.65 0.88 0.52]]


**🌟 Exercise 5 : Indexing Arrays**

In [ ]:

arr = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print(arr[1])


[20 21 22 23 24]


**🌟 Exercise 6 : Reversing elements**

In [ ]:

arr = np.array(range(10))
print(arr[::1])

[0 1 2 3 4 5 6 7 8 9]


**🌟 Exercise 7 : Identity Matrix**

In [ ]:

arr = np.identity(4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**🌟 Exercise 8 : Simple Aggregate Funcs**

In [ ]:
# Exemple de tableau 1D
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Calcul de la somme
sum_array = np.sum(array)

# Calcul de la moyenne
avg_array = np.mean(array)

print(f"Sum: {sum_array}, Average: {avg_array}")

Sum: 45, Average: 4.5


**🌟 Exercise 9 : Create Array and Change its Structure**

In [ ]:
# Créer un tableau de 1 à 20
array = np.arange(1, 21)

# Reshaper en matrice 4x5
matrix = array.reshape(4, 5)

print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


**🌟 Exercise 10 : Conditional Selection of Values**

In [ ]:
# Tableau exemple
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extraire les nombres impairs
odd_numbers = array[array % 2 == 1]

print(odd_numbers)

[1 3 5 7 9]
