<a href="https://colab.research.google.com/github/moaadouhmad99-ops/DI_Bootcamp/blob/main/Week5/Day1/Ex_XP_Gold_W5_D1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Exercise 1 : Minimum and Maximum of Random Array**

In [5]:
import numpy as np

# Create a 5x5 array with random values
arr = np.random.rand(5,5)

# Find minimum and maximum values
minimum_value = arr.min()
maximum_value = arr.max()

print("Random 5x5 array:\n", arr)
print("\nMinimum value:", minimum_value)
print("Maximum value:", maximum_value)

Random 5x5 array:
 [[0.59161417 0.90721156 0.70089511 0.98480294 0.09058709]
 [0.15630678 0.5382834  0.96123552 0.98809658 0.12559929]
 [0.1820296  0.2381092  0.90301156 0.73434307 0.8565385 ]
 [0.77023965 0.39451663 0.93193465 0.62454102 0.87611824]
 [0.86730126 0.19689682 0.69217346 0.0031251  0.2571178 ]]

Minimum value: 0.0031251001741601225
Maximum value: 0.9880965759376276


# **Exercise 2 : Matrix Normalization**

In [12]:
import numpy as np

# Create a 3x3 random matrix
A = np.random.rand(3, 3)

# Compute mean and standard deviation
mean_A = A.mean()
std_A = A.std()

# Normalize the matrix
A_normalized = (A - mean_A) / std_A

print("Original matrix:\n", A)
print("\nMean:", mean_A)
print("Standard deviation:", std_A)
print("\nNormalized matrix:\n", A_normalized)


Original matrix:
 [[0.40356516 0.87042125 0.66778467]
 [0.40276001 0.70691689 0.69120412]
 [0.47994673 0.24566532 0.29119116]]

Mean: 0.5288283674033054
Standard deviation: 0.2013019364502781

Normalized matrix:
 [[-0.62226531  1.696918    0.69028795]
 [-0.62626499  0.88468362  0.80662787]
 [-0.24282747 -1.40665834 -1.18050134]]


# **Exercise 3 : Evenly Spaced Elements in Array**

In [23]:
import numpy as np
array_1D = np.array(np.linspace(0, 10, 50))
print(array_1D)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


# **Exercise 4 : Matrix Multiplication**

In [100]:
import numpy as np
A = np.random.rand(5, 3)
B = np.random.rand(3, 2)
C = np.dot(A, B)
print("A=",A)
print("B=",B)
print("A*B=",C)


A= [[0.15901539 0.51008649 0.98869514]
 [0.83682525 0.48742172 0.56073387]
 [0.07043121 0.92635317 0.80611322]
 [0.21819631 0.99010679 0.92663776]
 [0.4897628  0.82991116 0.71292852]]
B= [[0.53013507 0.06068813]
 [0.55355547 0.19088141]
 [0.63314829 0.50096929]]
A*B= [[0.99265145 0.60232228]
 [1.06847307 0.42473555]
 [1.06051513 0.58493591]
 [1.25045167 0.66645197]
 [1.17043177 0.54529269]]


# **Exercise 5**

In [105]:
import numpy as np

# Creating two matrices
A = np.array(np.random.rand(4,3))
B = np.array(np.random.rand(3,4))

# Performing matrix multiplication
result = A @ B  # Equivalent to np.dot(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Multiplication Result:\n", result)


Matrix A:
 [[0.30220881 0.79372537 0.40203348]
 [0.49086412 0.55395396 0.5073148 ]
 [0.0895788  0.2450066  0.85171298]
 [0.3616024  0.94399487 0.81434361]]
Matrix B:
 [[0.47186089 0.31375316 0.76805959 0.71724868]
 [0.32753674 0.3177604  0.19317731 0.43106139]
 [0.73325045 0.62187925 0.72109376 0.4500292 ]]
Matrix Multiplication Result:
 [[0.69736597 0.59704973 0.67534794 0.73983003]
 [0.78504867 0.64552335 0.84984577 0.81916628]
 [0.74703632 0.63562165 0.73029648 0.55315887]
 [1.07693685 0.91984147 1.04730868 1.03275699]]
